$engine: 3
$onesync: on

name: ShadowCity RP Core
version: 0.1.0
author: ShadowCity RP
description: Custom txAdmin recipe for ShadowCity RP with SCRP framework and oxmysql.

variables:
    recipeGitRepo: SaschaB88/shadow_city_rp-framework
    recipeGitRef: master

tasks:
    - action: connect_database

    - action: download_github
      src: https://github.com/citizenfx/cfx-server-data
      ref: master
      subpath: resources
      dest: ./resources/[cfx-default]

    - action: download_file
      url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
      path: ./tmp/oxmysql.zip

    - action: unzip
      src: ./tmp/oxmysql.zip
      dest: ./resources/[standalone]

    - action: download_github
      src: https://github.com/{{recipeGitRepo}}
      ref: "{{recipeGitRef}}"
      dest: ./tmp/scrp

    - action: move_path
      src: ./tmp/scrp/resources/[shadowcity]
      dest: ./resources/[shadowcity]

    - action: move_path
      src: ./tmp/scrp/server.cfg
      dest: ./server.cfg

    - action: remove_path
      path: ./tmp